---
title: "Data Wrangling with R and the tidyverse"
description: |
  A Short Course using R and the Tidyverse suite of tools.
author:
- name: Kieran Healy
  url: https://kieranhealy.org
date: "`r Sys.Date()`"
output: distill::distill_article
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Course Description

R is a free and open-source package for statistical analysis that is widely used in the social, health, physical, and computational sciences. R is powerful, flexible, and has excellent graphics capabilities. It also has a large and rapidly growing community of users. Although there are a variety of approaches to working with data in R, in recent years, the "[tidyverse](https://www.tidyverse.org)" has emerged as a cohesive and consistent approach to the everyday tasks of data wrangling and analysis. The [tidyverse](https://www.tidyverse.org) is a suite of tools for data management, manipulation, analysis, and visualization within the R software environment for statistical computing. This seminar provides an intensive, hands-on introduction to using tidyverse tools for doing your own work. 

The course is not focused on particular statistical methods or modeling techniques. Rather, we will learn how to accomplish everyday tasks that statistical analysis depends on but which are rarely taught in detail in their own right. These include topics such as getting your own data into R, exploring the structure of your data, recoding variables and reshaping tables, and presenting summary tabulations and graphs of this work. Throughout the course we will emphasize how R and the tidyverse "thinks". Every dataset is different, especially at stage where it still needs further cleaning or arranging before it can be easily analyzed or effectively presented. This course will teach you the logic and implicit "flow of action" behind the tidyverse's tools, giving you the ability to apply and extend this way of thinking when working with your own data and its particular challenges. 

# Computing 

This remote seminar is held via [Zoom](https://zoom.us/), a free video conferencing application. Instructions for joining a session via Zoom are available [here](https://support.zoom.us/hc/en-us/articles/201362193-Joining-a-Meeting). Before the seminar begins, you will receive an email with the meeting code and password you must use to join.

We will be working with the most recent stable versions of R and RStudio, as well as with a number of additional packages. You will need to install R, RStudio, and the necessary packages on your own computer.

### Install R on your computer

Begin by installing R (<http://cloud.r-project.org>). Choose the version appropriate for your computing platform: 


- If you use macOS with an Apple Silicon processor (i.e. an M1, M2, or M3 processor), then install [R for macOS's Apple Silicon build](https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.4.1-arm64.pkg). This version does not work on older, Intel-based Macs.

- If you use macOS with an Intel processor, then install [R for macOS's Intel build](https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.4.1-x86_64.pkg). 

- If you use Microsoft Windows, then install [R for Windows](https://cran.r-project.org/bin/windows/base/R-4.4.1-win.exe)

- If you use Linux, [choose a distribution](https://cloud.r-project.org/bin/linux/) and install it.

### Install RStudio on your computer

- If you use macOS (whether Apple Silicon or Intel), [install this version of RStudio](https://download1.rstudio.org/electron/macos/RStudio-2024.04.2-764.dmg)

- If you use Windows, [install this version of RStudio](https://download1.rstudio.org/electron/windows/RStudio-2024.04.2-764.exe)

- If you use Linux, [choose your distribution from the download page](https://posit.co/download/rstudio-desktop/)

### Installing some additional packages

- Once R and RStudio are installed, launch RStudio. Either carefully type in or copy-and-paste the following lines of code at R’s command prompt, located in the RStudio window named “Console”, and then hit return. In the code below, the `<-` arrow is made up of two keystrokes, first `<` and then the short dash or minus symbol, `-`.


```R
my_packages <- c("tidyverse", "babynames", "broom", "drat", "gapminder",  
                  "here", "janitor", "naniar", "palmerpenguins", "remotes",
                  "skimr", "slider", "socviz", "usethis", "visdat", "reprex")

install.packages(my_packages, repos = "http://cran.rstudio.com")

# Be patient!
data_packages <- paste0("kjhealy/", c("covdata", "congress", "nycdogs", "ukelection2019", "uscenpops"))
remotes::install_github(data_packages)

```

Installing these packages may take a little time. Once you have completed this step, you'll be ready to download the course packet and begin.

### Optional step: get set up on GitHub 

GitHub is a software development platform and service that is widely used by R Developers. You can [read some background on it from an R user's point of view here](https://happygitwithr.com/big-picture.html).

If you do not have one already, it will be useful to create a GitHub account and obtain a GitHub Personal Access Token. This is _not required_ for the course, but would be helpful to have. After you have installed R and RStudio, to get set up, read and _carefully follow_ the instructions here:

- Register a [GitHub Account](https://happygitwithr.com/github-acct.html)
- Install [Git](https://happygitwithr.com/install-git) and a [Git Client](https://happygitwithr.com/git-client.html)
- Get a [Personal Access Token](https://happygitwithr.com/https-pat)
- Connect to [GitHub](https://happygitwithr.com/push-pull-github.html)

Again, setting up a GitHub account is _not required_ to fully participate in the course.



# The Course Packet

In addition to installing the software above, we will work with a packet of material that includes all the slides for the course, all the code we will write, and additional, relatively unprocessed or otherwise awkward datasets that we will use as examples. 


I recommend waiting until shortly before the course begins to download the course packet, as it may change before we begin. The course packet is available as a zip file at this link:

[Download the Data Wrangling Course Packet](https://github.com/kjhealy/data_wrangling_notes/archive/refs/heads/main.zip)

_Notes:_ 

- The packet has a `README.md` file explaining what it contains.

- Once you have downloaded the packet, _make sure you uncompress the zip file into a folder_. Some versions of the Windows file manager allow you to browse the contents of a zip file without actually uncompressing it. For the packet to be useful, make sure it is uncompressed.

- At the end of the course, I will update the slides and working files as needed to reflect the material we covered. This will allow additional examples or cases that come up during the seminar to be incorporated into the course packet.


# The Course Slack

During the seminar we will use a [Slack](https://slack.com) to provide an additional channel of communication outside the lectures. You will recieve details about how to sign up prior to the course. I encourage you to use the Slack to ask questions, share code snippets, and discuss matters arising in the seminar, from "I can't get this to work" troubleshooting on up to any other more general comments or queries about the material we are covering.

# Course Outline

## 1. Get in the right frame of mind

- Why plain-text data analysis?
- Why R got that way
- The RStudio IDE and how it works
- Pipelining your code
- First examples

## 2. Understand R and how it thinks

- Reproduce your own research with RMarkdown
- Make the RStudio work for you
- What is "tidy" about the tidyverse?
- The nuts and bolts of R
- How to pipeline your code, and why
- R's objects, functions, packages, and environments

## 3. View, tabulate and summarize data with `dplyr`

- Filter, select, mutate, and summarize tables
- Understand grouping and the logic of working with grouped data
- Perform calculations on the columns of tables, and on the rows
- Work `across()` columns
- Manipulate column names, arrange rows
- Write functions to quickly summarize data

## 4. Reshape your data with `tidyr`

- What's tidy about tidy data?
- Move back and forth between wide and long data
- Split, separate, and recode your observations
- Make your life easier before you reshape your data
- Expand and complete datasets

## 5. Understand the power of regular expressions

- String manipulation with `stringr`
- The language of rexeps and why it is useful

## 6. Get your data into R with `readr` and `haven`, and clean it

- Read in different plain-text formats
- Import from Stata
- Import multiple files using `map()` and its friends
- Clean awkward or messy data 
- Manage and visualize missing values
- Work with categorical data and factors using `forcats`

## 7. Iterate on data with `dplyr`, `purrr`, and `broom`

- Learn how to compactly analyze subsets of your data
- Learn the elements of table joins
- Extend tidy principles to modeling with `broom`
- Efficiently fit models and summarize their output in tables or graphs

## 8. Be tidy without tears

- Get help from the `janitor` package
- Make your life easier with `usethis` 
- Make it easier for others to help you with `reprex` 
- How to document your data as you go
- Explore the wider world of tidyverse-friendly packages and tools
