---
title: "Office Hour 2"
author: "Kieran Healy"
date: "4/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}

library(tidyverse)
library(here)
library(socviz)
```

# Reading and cleaning data: examples

```{r}
prison <- read_csv(here("data", "prison_jail_1970_2016.csv")) %>% 
  janitor::clean_names()

prison
```


```{r}
prison %>% select(year, us_total_pris_pop,
                state_total_pris_pop,
                nc_total_pris_pop) %>%
  pivot_longer(cols = c(us_total_pris_pop:nc_total_pris_pop), 
               names_to = "series", values_to = "count") %>%
  mutate(series = recode(series, us_total_pris_pop = "US",
                           state_total_pris_pop = "State",
                           nc_total_pris_pop = "NC")) %>% 
  ggplot(aes(x = year, y = count, linetype = series)) +
    geom_line() +
    scale_y_continuous(labels = scales::comma) +
    labs(x = "Year", y = "Count", linetype = NULL,
         title = "US, State, and NC Prison Populations 1970-2016") +
    theme(legend.position = "top")
 
  
```

```{r}
pew <- read_csv(here("data", "pew.csv")) %>% 
  janitor::clean_names() %>% 
  pivot_longer(x10k:dont_know_refused, names_to = "income", values_to = "n") %>% 
  mutate(
    income = str_replace_all(income, "x", "$"), 
    income = str_replace(income, "_", "-"), 
    income = str_replace(income, "dont-know_refused", "Don't Know/Refused"),
    income = str_replace(income, "-(\\d)", "-$\\1"))
```

```{r}
# 
# \bs\w+d\b

```

```{r}
qualtrics <- readxl::read_xlsx(here("data", "qualtrics.xlsx")) %>% 
  slice(-(1:2))

qualtrics2 <- read_csv(here("data", "qualtrics.csv")) %>% 
  slice(-(1:2))

```


```{r}
library(stringr)
library(lubridate)

chat <- read_lines(here("data", "chat.txt"))
chat
length(chat)

# Parsing the chat
chat_df <- tibble(
    time = as_datetime(paste(today(), str_extract(chat, "\\d{2}:\\d{2}:\\d{2}")), tz = "EST"),
    from = str_replace(chat, "(\\d{2}:\\d{2}:\\d{2} From )(.+?)( to Everyone .+?$)", "\\2"),
    message = str_replace(chat, "(\\d{2}:\\d{2}:\\d{2} From )(.+?)( to Everyone : )(.+?$)", "\\4")
)

chat_df %>% 
  group_by(from) %>% 
  tally() %>% 
  arrange(desc(n))

```


```{r}
organdata %>% 
  select(country, world)

organdata %>% 
  mutate(world2 = recode(world, Liberal = "A")) %>% 
  select(country, world, world2)
```

```{r}
starwars %>%
  select(name:mass, gender, species) %>%
  mutate(
    type = case_when(
      height > 200 | mass > 200 ~ "large",
      species == "Droid"        ~ "robot",
      name == "Darth Vader"  ~ "villain",
     TRUE                      ~ "other",
    )
  )

```

```{r}
gss_sm %>% 
  select(age) %>% 
  mutate(young = ifelse(age < 26, "Yes", "No"))

```


